apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-pod
          image: busybox:1.28
          command: ["sh", "-c", "until nslookup mongo-service.default.svc.cluster.local; do echo Aguardando o banco de dados; sleep 2; done"]
      containers:
      - name: api
        image: brenootsuka/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        resources:
          requests:
            memory: 32Mi
            cpu: 150m
          limits:
            memory: 64Mi
            cpu: 500m
        readinessProbe:
          httpGet:
            path: /read
            port: 80
            scheme: HTTP
          timeoutSeconds: 2
          failureThreshold: 3
          periodSeconds: 8
        livenessProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 16
          periodSeconds: 8
          timeoutSeconds: 2
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 80
            scheme: HTTP
          failureThreshold:  3
          periodSeconds: 8
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
        - name: Mongo__User
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_USERNAME 
        - name: Mongo__Password
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: MONGO_INITDB_ROOT_PASSWORD
