apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-mongo-pv
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: "/volumes/mongodb"
  